# Copyright (c) 2025 The.Thanh Nguyen <the.nguyen.yf@outlook.com>
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: thenguyenyf
      url-base: https://github.com/thanhthe23

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - edtt
          - fatfs
          - liblc3
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mcuboot
          - mipi-sys-t
          - net-tools
          - open-amp
          - picolibc
          - segger
          - uoscore-uedhoc
          - zcbor
          - zscilib
          - openthread
    - name: hal_fsp
      remote: thenguyenyf
      repo-path: z-fsp
      revision: master
      path: modules/hal/hal_fsp
      submodules: true

self:
  path: fsp
